/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "% to next level": "% 到下一级",
    "10% energy regen speed (+": "10% 能量回复速度 (+",
    "2 - Consume vanilla honey": "2 - 食用香草蜂蜜",
    "1 - Consume honey": "1 - 食用蜂蜜",
    "A - Attack": "A - 攻击",
    "All blood production is doubled": "所有的血液产量都翻倍",
    "All blood production is multiplied by 10": "所有血液产量乘以10",
    "All blood production is tripled": "所有血液产量增加三倍",
    "Altar": "祭坛",
    "Attack": "攻击",
    "Attack damage": "攻击伤害",
    "Big spider": "大蜘蛛",
    "blood gems": "血宝石",
    "Blood gems": "血宝石",
    "Blue rune": "蓝色符文",
    "Blue* rune": "蓝色*符文",
    "Cocoa bars": "可可棒",
    "dark bar": "黑条",
    "Dark bar (not unlocked": "黑条（未解锁",
    "Dark bars": "黑条",
    "dark orb": "黑球",
    "Dark orbs": "黑球",
    "Dark orbs massively increase tier 6 XP gain": "黑暗球体大大增加了第 6 层 经验 的增益",
    "Dark orbs multiply blood production": "黑暗球体使血液产量成倍增加",
    "Double cocoa honey gain": "双倍可可蜂蜜增益",
    "Double cocoa honey gain again": "可可蜂蜜再次双倍增长",
    "Reset all progress for": "重置所有进度",
    "Return to stairwell": "返回楼梯间",
    "star bar": "星条",
    "Unlock": "解锁",
    "Vanilla honey": "香草蜂蜜",
    "Vanilla honey multiplies cocoa honey gain": "香草蜂蜜乘以可可蜂蜜增益",
    "Vanilla honey multiplies honeyplasm gain": "香草蜂蜜乘以蜜浆增益",
    "What's up? I'm Benji B. Smith. I'll happily smith": "这是怎么回事？ 我是本吉·B·史密斯。 我会很高兴地锻造",
    "Which gives multiple large boosts/bonuses": "这提供了多个大的提升/奖金",
    "Woah-oah my GOD, a CUSTOMER! Welcome, welcome! I have things! PLEASE BUY SOMETHING!!!!!!!": "哇哦我的上帝，一个客户！ 欢迎欢迎！ 我有东西！ 请买东西！！！！！！！",
    "You acquired": "你获得了",
    "You are in a seemingly endless stairwell. The stairs are carpeted in beige, and the walls are warm and bright. The landings are lit by continuous windows with nothing but white on the other side.": "你在一个看似没有尽头的楼梯间。 楼梯铺着米色的地毯，墙壁温暖而明亮。 楼梯平台被连续的窗户照亮，另一边只有白色。",
    "You are on": "你在",
    "You died!": "你凉了！",
    "You feel safe to go up, but a paralyzing fear sets in when you try to go below the ground floor.": "你觉得上去很安全，但是当你试图去到一楼以下时，一种瘫痪的恐惧就会出现。",
    "You have beaten": "你打败了",
    "You've lost some of your XP.": "您丢失了一些 经验。",
    "Call upon the power of your SICK ASS GUNS to multiply golden honey gain by 25,000": "召唤你的 恶心的枪 的力量，将黄金蜂蜜增益乘以 25,000",
    "Enter this floor": "进入这个楼层",
    "Erase ALL PROGRESS to gain a": "擦除所有进度以获得",
    "Forge the": "锻造",
    "Flee (": "逃跑 (",
    "Hard reset": "硬复位",
    "Health": "生命值",
    "Honey": "蜂蜜",
    "Honeyplasm": "蜜浆",
    "Golden upgrades": "金色升级",
    "Golden honey": "金色蜂蜜",
    "Green rune": "绿色符文",
    "Green* rune": "绿色*符文",
    "Go up a floor": "往上一层",
    "Go down a floor": "往下一层",
    "giving you": "给了你",
    "Time until attack": "攻击前的时间",
    "Tip": "提示",
    "Tip history": "历史提示",
    "To ground floor": "到一层",
    "Total XP": "总计经验",
    "Turn all of your cocoa honey into a": "把你所有的可可蜂蜜变成",
    "Up arrow - Go up a floor": "上箭头 - 往上一层楼",
    "This game uses": "这个游戏使用了",
    "This box is way too big for this message.": "这个框对于这条消息来说太大了。",
    "super blood gem": "超级血宝石",
    "Right arrow - Enter floor": "向右箭头 - 进入楼层",
    "Right arrow - Explore new room": "右箭头 - 探索新房间",
    "Requires": "需要",
    "Remove XP softcap": "移除经验软上限",
    "Reinhardt's House": "莱因哈特之家",
    "Red* rune": "红色*符文",
    "Red rune": "红色符文",
    "P - Prestige": "P - 声望",
    "None": "无",
    "Next requires": "下一个需要",
    "Monsters killed": "杀死的怪物",
    "Monster blood upgrades": "怪物血升级",
    "Level": "等级",
    "levels": "等级",
    "Loosely inspired by": "灵感来自",
    "monster blood": "怪物血",
    "Monster blood production is massively increased, but lose all producers,": "怪物血产量大幅增加，但失去所有生产者，",
    "Monster blood production is pentated by 2, but lose all producers,": "怪物血产量减2，但失去所有生产者，",
    "Monster blood production is squared": "怪物血产量平方",
    "Monster blood production is squared": "怪物血产量再次平方",
    "Monster blood production is tetrated by 2": "怪物血量减少 2",
    "Craft the": "制作",
    "Created by Demonin": "由恶魔创建",
    "Current bonuses": "当前奖励",
    "Damage": "伤害",
    "Damn, okay": "该死的，好吧",
    "Down arrow - Go down a floor": "下箭头 - 往下一层",
    "End": "终点",
    "Enemies past floor 100 drop honey": "超过楼层 100 的敌人会掉落蜂蜜",
    "Enemies' first attack takes 4.5s": "敌人的第一次攻击需要 4.5 秒",
    "Energy": "能量",
    "Enter another room": "进入另一个房间",
    "F - Flee": "F - 逃跑",
    "Floor difficulty multiplies golden honey gain": "楼层难度乘以金色蜂蜜增益",
    "Forge your hyper gem into a star gem": "将您的超级宝石锻造成一颗星星宝石",
    "Forge your lucky ring into a shadow ring": "将你的幸运戒指锻造成暗影戒指",
    "Gain more buttons for easy travelling": "获得更多按钮，轻松旅行",
    "gem eels,": "宝石鳗鱼，",
    "Golden eel": "金色鳗鱼",
    "HP is set to max HP when killing an enemy": "杀死敌人时HP设置为最大HP",
    "hyper gem": "超级宝石",
    "hyperplasm": "超浆",
    "Hyperplasm": "超浆",
    "Hyperplasm (not unlocked": "超浆 (未解锁",
    "Hyperplasm gain is far greater, but so is the cost": "超浆增益要大得多，但成本也是如此",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Double golden honey gain (": "双倍金色蜂蜜增益（",
    "Endless Stairwell": "无尽的楼梯间",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Gain floor (.+) teleport button$/, '获得 $1 层传送按钮'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Gain (.+) free tier (.+) producers$/, '获得 $1 个免费的 $2 阶生产者'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) cocoa bar$/, '$1 可可棒'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^To floor ([\d\.,]+)$/, '到楼层 $1'],
    [/^Buy a tier ([\d\.,]+) blood producer$/, '购买 $1 阶血液生产商'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Costs (.+) cocoa honey$/, '成本 $1 可可蜂蜜'],
    [/^Costs (.+) honeyplasm$/, '成本 $1 蜜浆'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Requires (.+) star bars$/, '需要 $1 星条'],
    [/^Requires (.+) star bar$/, '需要 $1 星条'],
    [/^Requires (.+) blood gems$/, '需要 $1 血宝石'],
    [/^Requires (.+) hyperplasm$/, '需要 $1 超浆'],
    [/^Requires (.+) cocoa honey$/, '需要 $1 可可蜂蜜'],
    [/^Requires (.+) cocoa honey and (.+) dark orbs$/, '需要 $1 可可蜂蜜 和 $2 黑暗球体'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);